Person.create!(:first_name=>"Kristian", :last_name=>"Knevitt", :email=>"kristian.knevitt@gmail.com", :phone=>"07827813794", :twitter=>"knev123")
Person.create!(:first_name=>"Dan", :last_name=>"Steele")
Person.create!(:first_name=>"Lyra", :last_name=>"Peppa")
Person.create!(:first_name=>"Kin", :last_name=>"Bang")
Person.create!(:first_name=>"Dan", :last_name=>"Garland")
Person.create!(:first_name=>"Richard", :last_name=>"Johnson")