Person.create!(:first_name=>"Kristian", :last_name=>"Knevitt", :email=>"kristian.knevitt@gmail.com", :phone=>"07827813794", :twitter=>"knev123")
Person.create!(:first_name=>"Dan", :last_name=>"Steele", :role=>"Trainee")
Person.create!(:first_name=>"Lyra", :last_name=>"Peppa")
Person.create!(:first_name=>"Kin", :last_name=>"Bang")
Person.create!(:first_name=>"Dan", :last_name=>"Garland", :role=>"Instructor")
Person.create!(:first_name=>"Richard", :last_name=>"Johnson")

User.create!(:user_name=>"kknevitt", :password=>"abc123")
User.create!(:user_name=>"testinguser", :password=>"abc123")
User.create!(:user_name=>"testinguser2", :password=>"abc123")
User.create!(:user_name=>"testinguser3", :password=>"abc123")
User.create!(:user_name=>"testinguser4", :password=>"abc123")
